# Generated by Django 4.2.29 on 2026-04-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('time_slot', 'section')},
        ),
    ]
