# Generated by Django 4.2.29 on 2026-04-14 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_timetable_section_alter_timetable_time_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['section', 'time_slot']},
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. If provided without hours, auto-converts.', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], default='theory', max_length=10),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_lab_continuation',
            field=models.BooleanField(default=False, help_text='True for 2nd+ slots of a multi-slot lab block.'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduler.classsection'),
        ),
    ]
