# Generated by Django 4.2.29 on 2026-04-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_classsection_alter_timetable_options_subject_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Reasoning metadata: why this subject was placed in this slot.'),
        ),
    ]
