# Generated by Django 6.0.3 on 2026-04-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_timetable_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_lab', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_hours_per_week',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lab_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='is_lab_continuation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.room'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('teacher', 'time_slot'), name='unique_teacher_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('room', 'time_slot'), name='unique_room_per_slot'),
        ),
    ]
