# Generated by Django 6.0.3 on 2026-04-15 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_room_teacher_max_hours_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_room_per_slot',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_hours_per_week',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lab_group_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.room'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'time_slot'), name='unique_room_per_slot'),
        ),
    ]
